export {
	FEYNMAN_CONFIG_PATH as WEB_SEARCH_CONFIG_PATH,
	WEB_SEARCH_PROVIDERS,
	configureWebSearchProvider,
	formatWebSearchDoctorLines,
	getConfiguredWebSearchProvider,
	getWebSearchProviderById,
	getWebSearchStatus,
	hasConfiguredWebProvider,
	hasGeminiApiKey,
	hasPerplexityApiKey,
	loadWebSearchConfig,
	saveWebSearchConfig,
	type PiWebSearchProvider,
	type WebSearchConfig,
	type WebSearchProviderDefinition,
	type WebSearchProviderId,
	type WebSearchStatus,
} from "./config/feynman-config.js";
